version: '3'

services:
  garage-remote:
    image: amcolash/garage-remote
    container_name: garage-remote
    build: ./
    network_mode: 'host'
    volumes:
      - ./.cert:/usr/src/app/.cert
    entrypoint: npm run docker
    env_file:
      - .env
    restart: unless-stopped
